name: Deploy to github pages

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Set up wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0

    - name: Build
      run: |
        npm install 
        npm run build

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ghpusher

    - name: 
      run: |
        git config --global user.email "dbradf@gmail.com"
        git config --global user.name "David Bradford"
        git fetch origin gh-pages
        gh-pusher --build-dir dist

